# =============================================================================
# RDS PostgreSQL — the internal customer-profile source and identity SPINE (SPEC §2/§6).
# Debezium captures its WAL, so logical replication MUST be on.
# =============================================================================

# Logical replication parameter group — the enabler for Debezium CDC.
#   rds.logical_replication=1 sets wal_level=logical (static -> requires reboot).
#   The other params tune replication-slot safety so a lagging Debezium connector
#   cannot silently drop WAL the connector still needs.
resource "aws_db_parameter_group" "postgres_logical" {
  name        = "${local.name_prefix}-pg-logical"
  family      = "postgres15"
  description = "PostgreSQL 15 with logical replication for Debezium CDC (SPEC §2/§6)."

  parameter {
    name         = "rds.logical_replication"
    value        = "1"
    apply_method = "pending-reboot" # static param — takes effect on next reboot
  }

  parameter {
    name  = "max_replication_slots"
    value = "10"
    apply_method = "pending-reboot"
  }

  parameter {
    name  = "max_wal_senders"
    value = "10"
    apply_method = "pending-reboot"
  }

  # Keep enough WAL for the connector to recover after a short outage.
  parameter {
    name  = "wal_sender_timeout"
    value = "0"
  }

  tags = merge(local.common_tags, { Name = "${local.name_prefix}-pg-logical" })
}

resource "aws_db_subnet_group" "postgres" {
  name       = "${local.name_prefix}-pg-subnets"
  subnet_ids = var.private_subnet_ids
  tags       = merge(local.common_tags, { Name = "${local.name_prefix}-pg-subnets" })
}

resource "aws_security_group" "postgres" {
  name        = "${local.name_prefix}-pg-sg"
  description = "PostgreSQL source DB — ingress only from MSK Connect / Debezium workers."
  vpc_id      = var.vpc_id

  # Ingress restricted to the MSK Connect security group (Debezium runs on MSK Connect).
  ingress {
    description     = "Debezium (MSK Connect) -> PostgreSQL"
    from_port       = 5432
    to_port         = 5432
    protocol        = "tcp"
    security_groups = [aws_security_group.msk.id]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  tags = merge(local.common_tags, { Name = "${local.name_prefix}-pg-sg" })
}

# Master credentials are generated by RDS and stored in Secrets Manager (never in TF/state
# as plaintext). Debezium reads the credential from Secrets Manager at connector deploy time.
resource "aws_db_instance" "postgres" {
  identifier     = "${local.name_prefix}-postgres"
  engine         = "postgres"
  engine_version = "15"

  instance_class        = var.rds_instance_class
  allocated_storage     = var.rds_allocated_storage_gb
  max_allocated_storage = var.rds_allocated_storage_gb * 5 # storage autoscaling headroom
  storage_type          = "gp3"
  storage_encrypted     = true
  kms_key_id            = aws_kms_key.platform.arn

  db_name  = "customer_profile"
  username = "credit_app"

  # Let RDS manage the master password in Secrets Manager (rotates, never in state).
  manage_master_user_password   = true
  master_user_secret_kms_key_id = aws_kms_key.platform.arn

  parameter_group_name   = aws_db_parameter_group.postgres_logical.name
  db_subnet_group_name   = aws_db_subnet_group.postgres.name
  vpc_security_group_ids = [aws_security_group.postgres.id]

  multi_az                = var.env == "prod"
  backup_retention_period = var.env == "prod" ? 14 : 7
  deletion_protection     = var.env == "prod"
  skip_final_snapshot     = var.env != "prod"
  final_snapshot_identifier = var.env == "prod" ? "${local.name_prefix}-postgres-final" : null

  performance_insights_enabled    = true
  performance_insights_kms_key_id = aws_kms_key.platform.arn

  tags = merge(local.common_tags, { Name = "${local.name_prefix}-postgres", role = "identity-spine" })
}
